apiVersion: apps/v1
kind: Deployment 
metadata:
    name: "todo-app"
spec:
    selector: 
        matchLabels:
            app: "task"
    replicas: 5
    template:
        metadata:
            labels:
                app: "task"
        spec:
            containers:
            - image: {{.Values.image}}
              imagePullPolicy: Always
              name: "todoapp"
              env:
                - name: DB_URL
                  value: mongodb://AWS:<insertYourPassword>@todo-db-prod-docdb-cluster.cluster-chyox4cuah7f.us-east-1.docdb.amazonaws.com
              ports:
              - containerPort: 27017
