apiVersion: v1
kind: Service
metadata:
    name: "todoapp"
spec:
    ports:
        - port: 443
          targetPort: 5000
          protocol: TCP
    type: LoadBalancer
    selector:
        app: "task"
